apiVersion: v1
kind: Service
metadata:
  name: spring-boot-k8s
  labels:
    app: spring-boot-k8s
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-k8s
    tier: backend